// eslint-disable-next-line import/no-anonymous-default-export
export default {
  "Header.login": "Đăng Nhập",
  "Header.signup": "Đăng Kí",
  "Welcome.title": "Chào mừng bạn đến với website tìm kiếm và cho thuê sân Pickleball",
  "Welcome.content1": "Tìm kiếm và đặt sân nhanh chóng",
  "Welcome.content2": "Quy trình thanh toán an toàn, hiệu quả",
  "Welcome.content3": "Hỗ trợ nhiều tính năng cho chủ sân ",
  "Welcome.USER.buttonContent": "ĐẶT NGAY",
  "Welcome.OWNER.buttonContent": "TẠO SÂN NGAY",
  "LoginPage.loginTitle": "ĐĂNG NHẬP",
  "LoginPage.signupTitle": "ĐĂNG KÍ",
  "LoginPage.emailFieldTitle": "Email / Tên đăng nhập",
  "LoginPage.emailPlaceholder": "Nhập email hoặc tên đăng nhập...",
  "LoginPage.nameFieldTitle": "Họ và tên",
  "LoginPage.lastNamePlaceholder": "Nhập họ và tên đệm...",
  "LoginPage.firstNamePlaceholder": "Nhập tên...",
  "LoginPage.passwordFieldTitle": "Mật khẩu",
  "LoginPage.passwordPlaceholder": "Nhập mật khẩu...",
  "LoginPage.confirmPasswordFieldTitle": "Xác nhận mật khẩu",
  "LoginPage.confirmPasswordPlaceholder": "Nhập lại mật khẩu...",
  "LoginPage.loginButton": "Đăng nhập",
  "LoginPage.signupButton": "Đăng kí",
  "LoginPage.loginGoogle": "Đăng nhập bằng Google",
  "LoginPage.signupGoogle": "Đăng kí bằng Google",
  "LoginPage.errorMissingFieldUsername": "Vui lòng nhập email/tên đăng nhập!",
  "LoginPage.errorMissingField": "Vui lòng nhập đầy đủ các trường!",
  "LoginPage.errorMissingFieldPassword": "Vui lòng nhập mật khẩu!",
  "LoginPage.errorConfirmPassword": "Vui lòng nhập lại đúng mật khẩu!",
  "LoginPage.errorLogin": "Tên đăng nhập hoặc mật khẩu sai!",
  "LoginPage.errorSignup": "Tên đăng nhập/email đã tồn tại!",
  "SearchPage.searchTitle": "Tìm kiếm sân Pickleball:",
  "SearchPage.searchPlaceholder": "Nhập tên sân, địa chỉ...",
  "CreateCourt.upImages": "Nhấn để tải ảnh lên",
  "CreateCourt.uploadImageButton": "Tải ảnh lên",
  "CreateCourt.imageError.type": "Chỉ chấp nhận file ảnh!",
  "CreateCourt.imageError.size": "Kích thước ảnh phải nhỏ hơn 5MB!",
  "CreateCourt.imageError.maxCount": "Chỉ được tải lên tối đa 8 ảnh!",
  "CreateCourt.imageError.upload": "Không thể tải ảnh lên. Vui lòng thử lại!",
  "CreateCourt.imageError.preview": "Không thể hiển thị ảnh. Vui lòng thử lại!",
  "CreateCourt.inputNamePlaceholder": "Nhập tên sân... ",
  "CreateCourt.inputAddressTitle": "Địa chỉ:",
  "CreateCourt.inputAddressPlaceholder": "Nhập địa chỉ sân ở đây...",
  "CreateCourt.inputDescriptionTitle": "Thông tin:",
  "CreateCourt.inputDescriptionPlaceholder": "Nhập thêm các thông tin khác...",
  "CreateCourt.inputTimeslotTitle": "Ca thuê:",
  "CreateCourt.inputNumberTitle": "Số sân:",
  "CreateCourt.inputTimeColumn": "Thời gian ",
  "CreateCourt.inputPriceColumn": "Đơn giá",
  "CreateCourt.addNewTimeslot": "Thêm ca mới:",
  "CreateCourt.button": "Thêm sân ngay",
  "CreateCourt.inputTimeError": "Vui lòng nhập đầy đủ thông tin!",
  "CreateCourt.timeError": "Thời gian bắt đầu phải nhỏ hơn thời gian kết thúc!",
  "CreateCourt.isOverlapping": "Khoảng thời gian bị trùng!",
  "CreateCourt.errorNotEnough": "Vui lòng nhập đầy đủ thông tin!",
  "CreateCourt.errorCreateCourt": "Lỗi khi tạo sân!",
  "CreateCourt.successCreateCourt": "Tạo sân thành công!",
  "DetailCourt.inputDatePlaceholder": "Chọn ngày thuê",
  "DetialCourt.yourChoiceTitle": "Bạn đang chọn",
  "DetailCourt.courtNumber": "Sân {number}",
  "DetailCourt.noteAvailable": "Còn trống",
  "DetailCourt.noteUnavailable": "Đã cho thuê",
  "DetailCourt.notePendding": "Đang chờ xác nhận",
  "DetailCourt.noteChoiced": "Bạn đã chọn",
  "DetailCourt.buttonSubmit": "Đặt sân ngay",
  "TableInvoice.header1": "Khung giờ",
  "TableInvoice.header2": "Sân",
  "TableInvoice.header3": "Đơn giá",
  "TableInvoice.total": "Tổng tiền:",
  "DetailCourt.emptyTimeslot": "Vui lòng chọn ngày thuê và sân!",
  "DetailCourt.emptyInvoice": "Bạn chưa chọn ca thuê nào!",
  "DetailCourt.unavailableTimeslot": "Sân này đã được cho thuê!",
  "DetailCourt.pendingTimeslot": "Sân này đang chờ xác nhận!",
}